[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "netgraph"
version = "0.0.1"
dependencies = [
    "nethogs",
    "influxdb-client"
]

[tool.autopep8]
aggressive = 2
max-line-length = 120